# .air.toml

[build]
  bin = "tmp/main"          # Output binary
  cmd = "go build -o tmp/main ." # Build command
  delay = 1000              # ms delay before rebuild
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_file = []
  follow_symlink = false
  log = "build-errors.log"
  poll = false
  send_interrupt = true

[log]
  time = true

[debug]
  enable = false
  force = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[env]
  APP_ENV = "development"
